// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-OpLa_dWaAY0fS6DZL_yT_o5TWyH0Ts',
    appId: '1:292432059407:android:5bc507540ba89085ad177a',
    messagingSenderId: '292432059407',
    projectId: 'food-order-42e98',
    storageBucket: 'food-order-42e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoyzLabtWuClLal3biY4dway-PdGZVbM',
    appId: '1:292432059407:ios:776e4815bd1e404dad177a',
    messagingSenderId: '292432059407',
    projectId: 'food-order-42e98',
    storageBucket: 'food-order-42e98.firebasestorage.app',
    androidClientId: '292432059407-o3qhd996mjjnq0japeu70etr7sfgjbrt.apps.googleusercontent.com',
    iosClientId: '292432059407-9am39olmhfhunk3fvegnah3l0l1f6uda.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderApp.dev',
  );
}
